<?php

use App\RecetaFinanciadorAnulacion;
use Illuminate\Database\Seeder;

class RecetaFinanciadorAnulacionSeeder extends Seeder
{
    public function run()
    {
        $financiadores = [
            [1,   'OSAPM'],
            [2,   'APOS'],
            [3,   'APRESS'],
            [4,   'GASES'],
            [5,   'CAJA NOTARIAL C. DE S.S. DEL COL. ESCR.'],
            [6,   'GALENO'],
            [7,   'GRUPO SAN NICOLÁS'],
            [9,   'LUIS PASTEUR'],
            [10,  'MEDICUS'],
            [11,  'MEDIFE'],
            [12,  'MET MEDICINA PRIVADA'],
            [13,  'OBSBA'],
            [14,  'OMINT'],
            [15,  'OPDEA'],
            [16,  'OSDIPP'],
            [17,  'OSMECON PLAN MEDICO MATANZA'],
            [18,  'OSMECON E. ECHEVERRÍA'],
            [19,  'OSMECON PLAN FAMILIA LOMAS DE ZAMORA'],
            [20,  'OSMECON SAMO MERENZA'],
            [21,  'SAMI - Circulo Medico de Trenque Lauquen'],
            [22,  'PROGRAMAS MÉDICOS'],
            [23,  'SCIS MEDICINA PRIVADA'],
            [24,  'SWISS MEDICAL'],
            [25,  'OSPUNC/A - Unicum Tandil'],
            [26,  'OSPF - Obra Social del Personal de Farmacia'],
            [27,  'INSTITUTO DE SEGUROS DE JUJUY'],
            [82,  'OSMECON EMPRESAS ESTEBAN ECHEVERRIA'],
            [83,  'OSMECON PLAN FAMILIA LOMAS DE ZAMORA'],
            [84,  'OSAM Asociacion Medica Pergamino'],
            [85,  'WILLIAM HOPE'],
            [88,  'PREVENCION SALUD'],
            [89,  'OSSEG'],
            [108, 'AMFFA (ASOC MUTUAL DE FARM. F. AMEGHINO)'],
            [112, 'AMUR'],
            [117, 'APSOT'],
            [131, 'CEMIC'],
            [141, 'CAJA SOCIAL COL. ESCRIBANOS PROV. Bs. As.'],
            [144, 'Camioneros Rio Negro - OSCOCA'],
            [145, 'Camioneros Santiago del Estero - OSCOCA'],
            [146, 'Camioneros Recolección Rosario - OSCOCA'],
            [149, 'CASA'],
            [160, 'CONSEJO DE PROFESIONALES CPCE'],
            [182, 'EXPERTA ART'],
            [220, 'IOSFA'],
            [221, 'OSER'],
            [224, 'IPS INSTITUTO PROV. DE SALUD DE SALTA'],
            [226, 'IPSST. (SEGURIDAD SOCIAL)'],
            [228, 'ISSN – INST. DE SEG. SOCIAL DEL NEUQUÉN'],
            [230, 'JERARQUICO'],
            [233, 'LA PEQUEÑA FAMILIA'],
            [241, 'MEDICIEN'],
            [249, 'MPN - MEDICAMENTOS DE PRIMER NIVEL'],
            [252, 'OSPS MERCEDES BENZ ARG'],
            [268, 'OSADEF'],
            [275, 'OSARPHY'],
            [280, 'Camioneros Cordoba - OSCCPTAC'],
            [283, 'OSCHOCA'],
            [292, 'OSDEPYM'],
            [303, 'OSETRA'],
            [317, 'OSIERA'],
            [320, 'OSMATA'],
            [332, 'OSOETSYLARA'],
            [333, 'OSOSS'],
            [347, 'OSPAV'],
            [354, 'OSPE Petroleros'],
            [358, 'CONSTRUIR SALUD - OSPECON'],
            [368, 'OSPEPRI O. SOC. DE PETROLEROS PRIV. DE N'],
            [371, 'OSPERYH'],
            [375, 'OSPESTYPE'],
            [393, 'OSPIP'],
            [399, 'OSPJN - OS. DEL PODER JUDICIAL DE LA NAC'],
            [408, 'OSOPOCE'],
            [414, 'OSPRO - PERSONAL DE PRENSA DE ROSARIO'],
            [422, 'OSSACRA (AMA SALUD)'],
            [442, 'OSUTHGRA CABA Y GBA'],
            [455, 'PFA SUPERINTENDENCIA DE BIENESTAR'],
            [457, 'PLAN SALUD BRITANICO'],
            [459, 'PLENIT'],
            [476, 'QUALITAS'],
            [492, 'SAT (OBRA SOCIAL PERSONAL TELEVISION)'],
            [506, 'SMG LIFE'],
            [508, 'SOSUNC (OBRA SOCIAL UNIVERSITARIA)'],
            [509, 'SPF (SERVICIO PENITENCIARIO FEDERAL)'],
            [510, 'SPS SALUD'],
            [520, 'UNION PERSONAL'],
            [534, 'OSEP Catamarca'],
            [592, 'OSPBB PERSONAL DE PBBPOLISUR BAHIA BLANC'],
            [617, 'FEDERADA'],
            [618, 'Recetario Solidario'],
            [625, 'OSPA PORTUARIOS'],
            [637, 'TARMED'],
            [660, 'OSPFESIQYP'],
            [670, 'COMEDICA'],
            [689, 'GECROS'],
            [690, 'CONSEJO PROF CS EC CORDOBA'],
            [702, 'OSPFP PERSONAL FABRICAS DE PINTURA'],
            [706, 'Camioneros Entre Rios - OSCOCA'],
            [734, 'FAMILY SALUD'],
            [737, 'SALUD JUJUY'],
            [738, 'SAJU Salud'],
            [740, 'Colegio de Escribanos de Salta'],
            [747, 'Camioneros Catamarca - OSCOCA'],
            [748, 'Camioneros Chaco - OSCOCA'],
            [749, 'Camioneros Chubut - OSCOCA'],
            [750, 'Camioneros Corrientes - OSCOCA'],
            [751, 'Camioneros Formosa - OSCOCA'],
            [752, 'Camioneros Jujuy - OSCOCA'],
            [753, 'Camioneros La Pampa - OSCOCA'],
            [754, 'Camioneros La Rioja - OSCOCA'],
            [755, 'Camioneros Salta - OSCOCA'],
            [756, 'Camioneros San Juan - OSCOCA'],
            [757, 'Camioneros San Luis - OSCOCA'],
            [758, 'Camioneros Santa Cruz - OSCOCA'],
            [759, 'Camioneros Tierra del Fuego - OSCOCA'],
            [760, 'Camioneros Tucumán - OSCOCA'],
            [761, 'Camioneros Mendoza - OSCCPTAC'],
            [762, 'Camioneros Santa Fe - OSCCPTAC'],
            [764, 'Plan Salud Nueva Clínica Chacabuco Tandil'],
            [772, 'Sanitas Nubial'],
            [809, 'UNION PERSONAL - DIABETES'],
            [810, 'VALE SALUD'],
            [833, 'Plan Sustancias controladas Provincia de Jujuy'],
            [834, 'CONSEJO PROFESIONAL DE CIENCIAS ECONÓMI'],
            [835, 'Cobertura pública exclusiva / Particulares'],
            [921, 'OSSEG - Activa Salud'],
            [925, 'OSUTHGRA INTERIOR'],
            [926, 'HORIZONTE SEGUROS'],
            [929, 'SUME SALUD'],
            [933, 'OSPREN'],
            [934, 'MPRI-Instituto Médico Modelo de Solano'],
            [936, 'OSUNER'],
            [997, 'Osief'],
            // Nota: 112 también aparece como 'CAJA FORENSE - 2da Circ Santa Fe'
            // en el listado fuente; se mantiene 'AMUR' y se agrega la segunda entrada.
            [112, 'CAJA FORENSE - 2da Circ Santa Fe'],
        ];

        foreach ($financiadores as [$idFin, $nombre]) {
            RecetaFinanciadorAnulacion::firstOrCreate(
                ['id_financiador' => $idFin, 'nombre' => $nombre],
            );
        }
    }
}
